flatpressblog/flatpress

fp-includes/smarty/plugins/function.list_categories.php

php version: 5.4.45
flatpress version: 1.0.3

fix warning when list categories

---

fp-interface/themes/leggero/header.tpl

will automatically adapt to use http or https depending on current URI
closes #31

Use "//" instead of "http://" in googlefonts URI

---

comments.php
fp-interface/lang/de-de/lang.comments.php
fp-interface/lang/en-us/lang.comments.php
fp-plugins/prettyurls/htaccess-new
fp-plugins/prettyurls/htaccess.txt
fp-plugins/prettyurls/plugin.prettyurls.php

1. Added multilingual support for email subject line for new comments
2. Preventing directory browsing via PrettyURLS plugin when .htaccess is deleted by the user. ...as an addition to [#174](https://github.com/flatpressblog/flatpress/issues/174)
With best regards
Frank

Please add the following changes

---

fp-plugins/bbcode/plugin.bbcode.php
fp-plugins/bbcode/res/bbcode.css

this change resolves issue #192

this change resolves issue #192

---

defaults.php
fp-plugins/fpprotect/doc_fpprotect.txt
fp-plugins/fpprotect/plugin.fpprotect.php

Fixes #146
Can be optionally activated by the FlatPress admin
* Content Security Policy is an effective measure to protect your site from XSS attacks. By whitelisting sources for approved content, you can prevent the browser from loading malicious content.
* Permissions Policy is a new header that allows a site to control which features and APIs can be used in the browser.
* HTTP Strict Transport Security is an excellent feature to support on your site and strengthens your implementation of TLS by getting the User Agent to enforce the use of HTTPS.
* The X-Download-Options response header instructs the browser not to open the file directly but to offer it for download first. This mitigates some potential Social Engineering attacks.
* HTTP Strict Transport Security (HSTS for short) is a …

Hardens FlatPress via HTTP response header

---

fp-plugins/mediamanager/res/style.css
fp-plugins/mediamanager/tpls/admin.plugin.mediamanager.files.tpl

Fixes wrong HTML and outdated attributes in media manager plugin

---

fp-interface/sharedtpls/contact.tpl

include Smarty-function comment_form
Note:  Accessible Antispam Plugin is displayed, but you can send without mathematical solution
See #138

Accessible Antispam Plugin in contact form

---

.htaccess

Gives the PrettyURL plugin again the possibility to create a predefined .htaccess file with rewrite rules in the main directory.
Fixes #230

Delete the .htaccess file from the root directory

---

fp-interface/themes/leggero/leggero-v2/res/common.css

* IE fix in Leggero-v2 style is deprecated

removes IE fix

---

admin/panels/uploader/admin.uploader.php

- Fixes #217 - Vulnerability Stored XSS

Prevents upload of files with .xsig extension

---

CHANGELOG.md
fp-interface/themes/leggero/leggero-v2/res/admin.css
fp-interface/themes/leggero/leggero-v2/res/column.css
fp-interface/themes/leggero/leggero-v2/res/common.css
fp-interface/themes/leggero/leggero-v2/res/globals.css
fp-interface/themes/leggero/leggero-v2/res/style.css
fp-interface/themes/leggero/leggero-v2/style.conf.php

This PR is a supplement for PR #259 and includes:
- Text now keeps distance to a right or left floating BBcode video.
- Leggero v2 version bump
- small correction in the changelog
- I was once so cheeky and added myself to the existing style contributors :-P .

Makeup Leggero-v2 Style supplement

---

fp-defaults/settings-defaults.php

#198 supplement
Now the correct language is displayed in the admin area after the automatic detection of the language abbreviation.

#198 supplement

---

fp-interface/lang/browserlang.php
setup/lang/lang.sl-si.php

Supplement to Commit 164fab4 Slovenian translation
The automatic detection of the language ([browserlang.php](https://github.com/flatpressblog/flatpress/blob/master/fp-interface/lang/browserlang.php)) only works if the language file is also available for the setup. Otherwise, the setup will not be started. Theoretically, you could also copy the English language file and rename it to the one you want.
With best regards
Frank

Supplement to Commit 164fab4 Slovenian translation

---

fp-includes/fp-smartyplugins/function.list_categories.php
fp-interface/lang/cs-cz/lang.default.php
fp-interface/lang/da-dk/lang.default.php
fp-interface/lang/de-de/lang.default.php
fp-interface/lang/el-gr/lang.default.php
fp-interface/lang/en-us/lang.default.php
fp-interface/lang/es-es/lang.default.php
fp-interface/lang/fr-fr/lang.default.php
fp-interface/lang/it-it/lang.default.php
fp-interface/lang/ja-jp/lang.default.php
fp-interface/lang/nl-nl/lang.default.php
fp-interface/lang/pt-br/lang.default.php
fp-interface/lang/sl-si/lang.default.php

- fixes #276
- Categories "unfiled" is now multilingual

Categories "unfiled" is now multilingual

---

fp-includes/fp-smartyplugins/validate_criteria.notEmpty.php
fp-plugins/bbcode/inc/stringparser.class.php

Fixes #294

---

fp-plugins/bbcode/plugin.bbcode.php

A small change in do_bbcode_url to allow admins to make links open new windows, etc.

Added the target attribute on links generated with do_bbcode_url

---

admin/panels/entry/admin.entry.write.tpl

- Meh, integrating several plugins with one action hook does not work properly. Therefore, a separate action hook has been added for each plugin.
- The sensitive DateChanger plugin gets a place above the subject input field
- To do: The plugins in the extra repo still need to be adjusted

Addition to #286

---

fp-plugins/bbcode/plugin.bbcode.php

- RSS-feed returns bbcode if add_action()

Fixes #225

---

fp-interface/lang/it-it/lang.admin.entry.php
fp-interface/lang/it-it/lang.admin.widgets.php
fp-interface/lang/it-it/lang.contact.php
fp-plugins/commentcenter/lang/lang.it-it.php
fp-plugins/mediamanager/lang/lang.it-it.php

Update of the Italian language files by Eagleman

---

fp-plugins/bbcode/lang/lang.cs-cz.php
fp-plugins/bbcode/lang/lang.da-dk.php
fp-plugins/bbcode/lang/lang.de-de.php
fp-plugins/bbcode/lang/lang.el-gr.php
fp-plugins/bbcode/lang/lang.en-us.php
fp-plugins/bbcode/lang/lang.es-es.php
fp-plugins/bbcode/lang/lang.fr-fr.php
fp-plugins/bbcode/lang/lang.it-it.php
fp-plugins/bbcode/lang/lang.ja-jp.php
fp-plugins/bbcode/lang/lang.nl-nl.php
fp-plugins/bbcode/lang/lang.pt-br.php
fp-plugins/bbcode/lang/lang.ru-ru.php
fp-plugins/bbcode/lang/lang.sl-si.php
fp-plugins/bbcode/tpls/toolbar.tpl

- Internationalized button titles ready
- Remnants of Mootools (plugin_jsutils) removed from the template

BBcode toolbar with translated titles

---

defaults.php
setup/main.php

- Sets the file and directory permissions from the FP main directory and its subdirectories when executing the setup.
- See #307

File and directory rights

---

fp-content/plugin_commentcenter/policies.txt
fp-plugins/commentcenter/plugin.commentcenter.php

Fixes: #101 | Comments must be authorized as standard

Fixes: #101 | Comments must be authorized

---

admin/panels/entry/admin.entry.write.tpl
admin/panels/static/admin.static.write.tpl
fp-interface/sharedtpls/comment-form.tpl
fp-plugins/emoticons/plugin.emoticons.php
fp-plugins/emoticons/res/emoticons.css
fp-plugins/emoticons/res/emoticons.js

- allows the integration of emoticons as UTFT-8 HTML entity via a toolbar
- the toolbar is available when creating/editing entries, static pages and in the comment function

Emoticons toolbar

---

fp-interface/themes/leggero/entry-default.tpl

- In the Leggero theme, the number of views is now also displayed when comments are locked

Fixes #346

---

fp-plugins/support/lang/lang.cs-cz.php
fp-plugins/support/lang/lang.da-dk.php
fp-plugins/support/lang/lang.de-de.php
fp-plugins/support/lang/lang.el-gr.php
fp-plugins/support/lang/lang.en-us.php
fp-plugins/support/lang/lang.es-es.php
fp-plugins/support/lang/lang.fr-fr.php
fp-plugins/support/lang/lang.it-it.php
fp-plugins/support/lang/lang.ja-jp.php
fp-plugins/support/lang/lang.nl-nl.php
fp-plugins/support/lang/lang.pt-br.php
fp-plugins/support/lang/lang.ru-ru.php
fp-plugins/support/lang/lang.sl-si.php
fp-plugins/support/plugin.support.php
fp-plugins/support/tpls/admin.plugin.support.tpl

- Support plugin: the global and local time is displayed

Closes #356

---

fp-interface/themes/leggero/flatmaas-rev/res/admin.css
fp-interface/themes/leggero/leggero-v2/res/admin.css
fp-interface/themes/leggero/leggero/res/admin.css
fp-plugins/support/lang/lang.cs-cz.php
fp-plugins/support/lang/lang.da-dk.php
fp-plugins/support/lang/lang.de-de.php
fp-plugins/support/lang/lang.el-gr.php
fp-plugins/support/lang/lang.en-us.php
fp-plugins/support/lang/lang.es-es.php
fp-plugins/support/lang/lang.fr-fr.php
fp-plugins/support/lang/lang.it-it.php
fp-plugins/support/lang/lang.ja-jp.php
fp-plugins/support/lang/lang.nl-nl.php
fp-plugins/support/lang/lang.pt-br.php
fp-plugins/support/lang/lang.ru-ru.php
fp-plugins/support/lang/lang.sl-si.php
fp-plugins/support/plugin.support.php
fp-plugins/support/res/support.css
fp-plugins/support/tpls/admin.plugin.support.tpl

- Support plugin shows timezone if possible
- PHP information in php.net style

Cumulative

---

admin/panels/maintain/admin.maintain.php

...all just copied, o ho, o ho. see https://github.com/flatpressblog/flatpress/blob/7f67bf347dce18914bbeb2bf072f23543f2fcc61/fp-plugins/lastcommentsadmin/plugin.lastcommentsadmin.php#L40

Closes #80

---

fp-plugins/stats/lang/lang.cs-cz.php
fp-plugins/stats/lang/lang.da-dk.php
fp-plugins/stats/lang/lang.de-de.php
fp-plugins/stats/lang/lang.el-gr.php
fp-plugins/stats/lang/lang.en-us.php
fp-plugins/stats/lang/lang.es-es.php
fp-plugins/stats/lang/lang.fr-fr.php
fp-plugins/stats/lang/lang.it-it.php
fp-plugins/stats/lang/lang.ja-jp.php
fp-plugins/stats/lang/lang.nl-nl.php
fp-plugins/stats/lang/lang.pt-br.php
fp-plugins/stats/lang/lang.ru-ru.php
fp-plugins/stats/lang/lang.sl-si.php
fp-plugins/stats/plugin.stats.php

 Outsourcing of the fixed statistics panel in a plugin

---

contact.php

- Register Smarty modifier is_numeric for errorlist.tpl
- Register Smarty modifier function_exists

Contact form | Supplement to 2e36211

---

login.php
search.php

- Register Smarty modifier is_numeric for errorlist.tpl
- Register Smarty modifier function_exists

Admin login, search | Supplement to 2e36211

---

comments.php
contact.php

- If the commenting/contacting party enters their website without http(s)://, https:// is prepended, then validated.

Solves #419

---

admin/panels/widgets/admin.widgets.default.php
defaults.php
fp-defaults/settings-defaults.php
fp-plugins/bbcode/plugin.bbcode.php
fp-plugins/cookiebanner/plugin.cookiebanner.php
fp-plugins/emoticons/plugin.emoticons.php
fp-plugins/fpprotect/plugin.fpprotect.php
fp-plugins/jquery/plugin.jquery.php
fp-plugins/lightbox2/plugin.lightbox2.php
fp-plugins/photoswipe/photoswipefunctions.class.php

- Fixes: Changing the plugin configuration causes the nonce value to be permanently written to the configuration. However, the purpose is that the nonce value changes every time the blog is called.

nonce attribute random value

---

fp-plugins/bbcode/plugin.bbcode.php

- If BBcode is allowed in comments, URL and LIST tags are now also converted from BBcode to HTML

[URL] and [LIST] tags in comments

---

fp-interface/sharedtpls/atom.tpl
fp-interface/sharedtpls/comment-atom.tpl
fp-interface/sharedtpls/comment-rss.tpl
fp-interface/sharedtpls/rss.tpl

- Atom feed comments relative reference URL replaced by absolute URL
- RSS feed subtitles only if subtitles are set

Supplement to #429

---

admin/panels/entry/admin.entry.write.tpl
admin/panels/static/admin.static.write.tpl
fp-plugins/bbcode/panels/admin.plugin.panel.bbcode.php
fp-plugins/bbcode/tpls/admin.plugin.bbcode.tpl

- BBcode plugin/ admin area: fixes the possibility to disable/enable the editor toolbar

BBcode plugin/ admin area: disable/enable the BBcode editor toolbar

---

fp-includes/core/core.language.php
fp-interface/lang/cs-cz/lang.conf.php
fp-interface/lang/da-dk/lang.conf.php
fp-interface/lang/de-de/lang.conf.php
fp-interface/lang/el-gr/lang.conf.php
fp-interface/lang/en-us/lang.conf.php
fp-interface/lang/es-es/lang.conf.php
fp-interface/lang/fr-fr/lang.conf.php
fp-interface/lang/it-it/lang.conf.php
fp-interface/lang/ja-jp/lang.conf.php
fp-interface/lang/nl-nl/lang.conf.php
fp-interface/lang/pt-br/lang.conf.php
fp-interface/lang/ru-ru/lang.conf.php
fp-interface/lang/sl-si/lang.conf.php
search.php

- Localize Smarty function {html_select_date} with LC_TIME

Fixes #158 | Localize Smarty function {html_select_date}

---

admin/panels/static/admin.static.list.php
admin/panels/static/admin.static.list.tpl
fp-defaults/settings-defaults.php
fp-includes/core/core.static.php
fp-interface/lang/cs-cz/lang.admin.static.php
fp-interface/lang/da-dk/lang.admin.static.php
fp-interface/lang/de-de/lang.admin.static.php
fp-interface/lang/el-gr/lang.admin.static.php
fp-interface/lang/en-us/lang.admin.static.php
fp-interface/lang/es-es/lang.admin.static.php
fp-interface/lang/fr-fr/lang.admin.static.php
fp-interface/lang/it-it/lang.admin.static.php
fp-interface/lang/ja-jp/lang.admin.static.php
fp-interface/lang/nl-nl/lang.admin.static.php
fp-interface/lang/pt-br/lang.admin.static.php
fp-interface/lang/ru-ru/lang.admin.static.php
fp-interface/lang/sl-si/lang.admin.static.php

- Optional natural sorting for static pages in the admin area

Optional natural sorting for static pages

---

fp-includes/core/core.session.php
fp-includes/core/core.system.php
fp-interface/lang/sl-si/lang.default.php
login.php

- In addition: Fixed an error in the Slovenian language file

Centralized check of an existing session

---

fp-includes/core/core.users.php

... and replaces it with a SHA-256 hash

Removes the clear name in the fpuser cookie

---

login.php

These changes make the login page more secure and better protected against possible attacks.
- Inputs are sanitized to ensure that they are processed securely.
- The user name is cleaned up before it is assigned to Smarty.

Input cleanup before assigned to Smarty

---

admin/panels/uploader/admin.uploader.php

- File uploads are validated and cleaned up more strictly.
- In addition, directory traversal attacks are prevented.

This closes #220 (file upload xss vulnerability)

---

admin/panels/entry/admin.entry.delete.php
admin/panels/entry/admin.entry.delete.tpl
admin/panels/static/admin.static.delete.php
admin/panels/static/admin.static.delete.tpl

- This strengthens both actions (delete entry/ static page) against XSS and CSRF attacks

Cleanup and validation before deleting an entry or static page | Re-Upload

---

admin/panels/config/admin.config.php
admin/panels/config/admin.config.tpl

- Drop-down selection instead of input field

Solves #340 |  Missing check of the character set input

---

fp-plugins/emoticons/plugin.emoticons.php
fp-plugins/emoticons/res/emoticons.js

- The Java script has been removed from the `<body>` area and is now inserted in the `<head>` area.
- Focusing in the input field now works more precisely

Update Emoticons plugin to version 1.1.2

---

admin/panels/entry/admin.entry.write.php
admin/panels/static/admin.static.write.php

- The author of the entries and static pages does not have to be the user of the admin area.

Author not Admin

---

admin/panels/config/admin.config.php
admin/panels/plugin/admin.plugin.php

Configuration panel:
Changes in input fields and drop-down menus are immediately reflected in the user interface.
Plugin management panel:
Activating or deactivating plugins are immediately reflected in the user interface.

Solves #213 and #244

---

admin/panels/uploader/admin.uploader.php

- Vulnerability Name: Unrestricted File Upload with Hidden File Storage

Forbids the upload of hidden files

---

admin/panels/config/admin.config.php
fp-includes/fp-smartyplugins/validate_criteria.isValidDateOrTimeFormat.php

- This eliminates the XSS vulnerabilities
- Only a-zA-Z0-9:%.,- and spaces are now allowed in timeformat, dateformat, and dateformatshort.

Validation of timeformat, dateformat, and dateformatshort

---

defaults.php
fp-includes/core/core.cookie.php
fp-includes/core/core.users.php
fp-plugins/adminarea/plugin.adminarea.php
setup.php

- No user name or password in the cookie
- This update manages the user login and authentication via PHP sessions.

Session authentication

---

defaults.php
fp-plugins/bbcode/inc/isValidFileDownloadUrl.php
fp-plugins/bbcode/plugin.bbcode.php
get.php

- Removes the vulnerability Cross-Site Scripting (XSS) in get.php and the BBcode plugin
- Prevent directory traversal
Many thanks for reporting to @paragbagul111

Prevents (XSS) in file wrapper and the BBcode plugin

---

admin/panels/static/admin.static.write.php
admin/panels/static/admin.static.write.tpl

Many thanks for reporting to @paragbagul111

XSS vulnerability in the editor for static pages fixed

---

fp-plugins/seometataginfo/plugin.seometataginfo.php

- Removes the vulnerability Cross-Site Scripting (XSS) in the SEO Meta Tag Info  plugin
Many thanks for reporting to @paragbagul111

Prevents (XSS) in file wrapper and the SEO Meta Tag Info plugin

---

admin/panels/entry/admin.entry.write.php
admin/panels/static/admin.static.write.php
fp-plugins/seometataginfo/plugin.seometataginfo.php

More efficient cleaning of non-permitted characters

---

comments.php
contact.php

Fixes a problem that in some cases the success message is not displayed reliably.
- Before the page is reloaded, the success or failure message is passed to Smarty

Solves #420

---

fp-plugins/support/plugin.support.php
fp-plugins/support/res/support.js
fp-plugins/support/tpls/admin.plugin.support.tpl

- Removed unsafe onclick HTML method
- Interpolations removed

Support plugin revised

---

fp-plugins/support/lang/lang.cs-cz.php
fp-plugins/support/lang/lang.da-dk.php
fp-plugins/support/lang/lang.de-de.php
fp-plugins/support/lang/lang.el-gr.php
fp-plugins/support/lang/lang.en-us.php
fp-plugins/support/lang/lang.es-es.php
fp-plugins/support/lang/lang.fr-fr.php
fp-plugins/support/lang/lang.it-it.php
fp-plugins/support/lang/lang.ja-jp.php
fp-plugins/support/lang/lang.nl-nl.php
fp-plugins/support/lang/lang.pt-br.php
fp-plugins/support/lang/lang.ru-ru.php
fp-plugins/support/lang/lang.sl-si.php
fp-plugins/support/plugin.support.php
fp-plugins/support/tpls/admin.plugin.support.tpl

- Added check of the permissions of the config directory
- Further textual adjustments

Supplement Support Plugin

---

comments.php
fp-interface/sharedtpls/comment-atom.tpl

- Undefined array key "www" fixed
- Attempt to read property "value" on null fixed
- Modifier theme_comments_feed_link added

Fix comment Atom-Feed

---

fp-defaults/plugins.conf.php
fp-plugins/lastcomments/plugin.lastcomments.php
fp-plugins/lastcomments/tpls/plugin.lastcomments-atom.tpl
fp-plugins/lastcomments/tpls/plugin.lastcomments-feed.tpl

- Latest comments RSS and Atom feed added (Started a long time ago, but never finished.)

Update LastComment plugin to version 1.1.0

---

fp-plugins/lastcomments/plugin.lastcomments.php
fp-plugins/lastcomments/tpls/plugin.lastcomments-atom.tpl
fp-plugins/lastcomments/tpls/plugin.lastcomments-feed.tpl

- In the feed, the entry is now displayed after the name of the commenter

Supplement to #509

---

fp-plugins/lastcomments/plugin.lastcomments.php
fp-plugins/lastcomments/tpls/plugin.lastcomments-atom.tpl
fp-plugins/lastcomments/tpls/plugin.lastcomments-feed.tpl

- The BBcode plugin is used to convert BBcode tags into HTML for the RSS feed
- Invalid URL in the templates fixed

Supplement-2 to #509

---

fp-plugins/lastcomments/plugin.lastcomments.php
fp-plugins/lastcomments/tpls/plugin.lastcomments-atom.tpl
fp-plugins/lastcomments/tpls/plugin.lastcomments-feed.tpl

- RSS feed: Compatibility with some feed readers increased
- Dynamic, localized feed title instead of hard-coded
- Unclosed BBcode tags are no longer displayed in the shortened comment

Spplement-3 to #509

---

admin/panels/config/admin.config.php
fp-includes/core/core.users.php
fp-includes/core/core.wp-pluggable-funcs.php

- If the name of the admin has been changed, the previous admin will be deleted.
- After 3 seconds, the user is logged out

Supplement to #518

---

fp-interface/sharedtpls/search.tpl
search.php

Fixes encoding errors in localized months.

---

admin/panels/config/admin.config.php
comments.php
contact.php
fp-includes/core/core.date.php
fp-includes/fp-smartyplugins/validate_criteria.isValidAdminName.php
fp-includes/fp-smartyplugins/validate_criteria.isValidAdminPassword.php
fp-plugins/accessibleantispam/plugin.accessibleantispam.php
fp-plugins/prettyurls/plugin.prettyurls.php
fp-plugins/seometataginfo/plugin.seometataginfo.php
login.php

- Some functions are more robust against penetration tests
- Dynamic character set encoding

Fixes #529

---

defaults.php
fp-includes/core/core.filesystem.php

- Fixes the problem that preview images of the theme or style are not displayed when the permissions are restored (hidden hint from NHWS).

file and directory permissions

---

fp-interface/lang/ja-jp/lang.admin.config.php
fp-interface/lang/ja-jp/lang.default.php
fp-plugins/seometataginfo/lang/lang.ja-jp.php

- Many thanks to [Pea](https://mastodon.social/@peaonmob@mstdn.jp/113920307318810058) a.k. NHWS

supplement to #531

---

comments.php
fp-includes/core/core.utils.php
fp-interface/sharedtpls/comment-form.tpl
login.php

- Fixes various errors that occurred in the penetration test.
- utils_mail with header injection protection and rate limiting
- CSRF protection added for the comment function

Fixes various errors | Fixes #539 and fixes #534

---

fp-plugins/mediamanager/panels/panel.mediamanager.file.php

- Prevents the capture of .dlctr (Igor Kromins DownloadCounter) files

Mediamanger plugin | alphabetic order | Part 1 of #537

---

PERMISSIONS_JA-JP.md
fp-interface/lang/ja-jp/lang.admin.config.php
fp-interface/lang/ja-jp/lang.default.php
setup/lang/lang.ja-jp.php

Update japanese language package

---

comments.php
contact.php
login.php

- potentially unsafe inputs are cleaned up.
- No direct manipulation of SQL strings with unsafe input.
- Constants swapped for tokens

Avoidance of SQL injection

---

comments.php
contact.php
login.php

- Renew CSRF token to prevent replay attacks
- Token only reset after successful login

Token logic and security

---

fp-plugins/bbcode/plugin.bbcode.php
fp-plugins/mediamanager/plugin.mediamanager.php

Also:
Mediamanager: usecount data is only saved if it is not empty

BBcode-toolbar | sort by name | Fixes #537

---

fp-plugins/bbcode/plugin.bbcode.php
fp-plugins/photoswipe/photoswipefunctions.class.php

- BBcode: HTML output for embedded videos corrected.
- Photoswipe: Images are now also displayed when a Markdown parser is active.
- Photoswipe class: slightly more robust in case of missing images

Minor corrections

---

setup/lang/lang.ja-jp.php

Update of the Japanese language package

---

workflows/codeql-analysis.yml
workflows/phpstan.yml

- Job to increase code security ([CodeQL](https://github.com/github/codeql-action))
- Job to improve code quality ([PHPStan](https://github.com/php-actions/phpstan))

Integration of GitHub Action

---

admin/main.php
admin/panels/uploader/admin.uploader.browse.php
fp-includes/core/core.blogdb.php
fp-includes/core/core.bplustree.class.php
fp-includes/core/core.comment.php
fp-includes/core/core.draft.php
fp-includes/core/core.entry.php
fp-includes/core/core.fpdb.class.php
fp-includes/core/core.language.php
fp-includes/core/core.theme.php
fp-includes/core/core.users.php
fp-includes/core/core.utils.php
fp-includes/core/core.wp-formatting.php
fp-includes/core/core.wp-functions.php
fp-includes/core/core.wp-pluggable-funcs.php
fp-includes/fp-smartyplugins/block.admincontrols.php
fp-includes/fp-smartyplugins/function.list_categories.php
fp-includes/fp-smartyplugins/modifier.notempty.php
fp-includes/fp-smartyplugins/validate_criteria.isCCNum.php
fp-includes/fp-smartyplugins/validate_criteria.isFileSize.php
fp-includes/fp-smartyplugins/validate_criteria.isValidDateOrTimeFormat.php

PHPDoc and small improvements 001

---

fp-includes/smarty-4.5.5/libs/Smarty.class.php
fp-includes/smarty-4.5.5/libs/plugins/block.textformat.php
fp-includes/smarty-4.5.5/libs/plugins/function.cycle.php
fp-includes/smarty-4.5.5/libs/plugins/function.fetch.php
fp-includes/smarty-4.5.5/libs/plugins/function.html_checkboxes.php
fp-includes/smarty-4.5.5/libs/plugins/function.html_image.php
fp-includes/smarty-4.5.5/libs/plugins/function.html_options.php
fp-includes/smarty-4.5.5/libs/plugins/function.html_radios.php
fp-includes/smarty-4.5.5/libs/plugins/function.html_select_date.php
get.php
login.php

PHPDoc and small improvements 002

---

fp-includes/core/core.utils.php
fp-includes/smarty-4.5.5/libs/Smarty.class.php
fp-includes/smarty-4.5.5/libs/plugins/function.html_select_time.php

PHPDoc and small improvements 003

---

admin/panels/entry/admin.entry.cats.php
fp-plugins/gallerycaptions/admin_uploader_gallerycaptions.class.php

- category management panel
- Picture texts
- Entry-write panel is already secured against XSS

Close XSS vulnerabilities

---

fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_compile_foreach.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_templatecompilerbase.php

PHPDoc and small improvements 007

---

fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_compile_private_special_variable.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_config_file_compiler.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_configfileparser.php

PHPDoc and small improvements 009

---

fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_compile_section.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_errorhandler.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_extension_handler.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_gettags.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerfilter.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerobject.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerplugin.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerresource.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_setautoloadfilters.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_setdebugtemplate.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_setdefaultmodifiers.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_unregistercacheresource.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_unregisterfilter.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_unregisterobject.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_unregisterplugin.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_unregisterresource.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_resource_eval.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_resource_file.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_resource_stream.php

PHPDoc-and-small-improvements-009

---

fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_addautoloadfilters.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_runtime_cacheresourcefile.php

PHPDoc and small improvements 010

---

fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_literals.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registercacheresource.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerclass.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerdefaultconfighandler.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerdefaultpluginhandler.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_registerdefaulttemplatehandler.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_resource_string.php

PHPDoc and small improvements 012

---

fp-includes/fp-smartyplugins/resource.admin.php
fp-includes/fp-smartyplugins/resource.plugin.php
fp-includes/fp-smartyplugins/resource.shared.php
fp-includes/smarty-4.5.5/libs/Smarty.class.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_cacheresource_keyvaluestore.php

PHPDoc and small improvements 013

---

fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_compile_private_print_expression.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_compile_shared_inheritance.php

PHPDoc and small improvements 014

---

fp-includes/smarty-4.5.5/libs/Smarty.class.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_cacheresource_custom.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_debug.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_runtime_updatecache.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_template.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_templatecompilerbase.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_resource_recompiled.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_template_compiled.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_template_source.php

PHPStan level 3
... (string) does not accept null

PHPDoc and small improvements 015

---

admin/panels/static/admin.static.write.php
admin/panels/uploader/admin.uploader.browse.php
fp-includes/core/core.bplustree.class.php
fp-includes/core/core.cache.php
fp-includes/core/core.filesystem.php
fp-includes/core/core.fpdb.class.php
fp-includes/core/core.layout.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_data.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_getstreamvariable.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_method_mustcompile.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_nocache_insert.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_template.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_templatebase.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_resource.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_security.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_template_source.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_variable.php

PHPStan level 3 ... Access to an undefined property

PHPDoc and small improvements 016

---

fp-includes/core/core.layout.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_compilebase.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_nocache_insert.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree_code.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree_dq.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree_dqcontent.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree_tag.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree_template.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_parsetree_text.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_runtime_tplfunction.php
fp-includes/smarty-4.5.5/libs/sysplugins/smarty_internal_templatecompilerbase.php

PHPStan level 3
Fixes Call to an undefined method - method.notFound

PHPDoc and small improvements 017

---

fp-includes/core/core.bplustree.class.php
fp-includes/core/core.cache.php
fp-includes/core/core.draft.php
fp-includes/core/core.entry.php
fp-includes/core/core.filesystem.php
fp-includes/core/core.system.php

PHPDoc and small improvements 019

---

admin/includes/panels.prototypes.php
fp-includes/core/core.bplustree.class.php

rollback-2239

---

admin/includes/panels.prototypes.php
fp-includes/core/core.bplustree.class.php
fp-includes/core/core.date.php
fp-includes/core/core.entry.php
fp-includes/core/core.fpdb.class.php
fp-includes/core/core.language.php
fp-includes/core/core.theme.php

PHPDoc and small improvements 020

---

fp-includes/core/core.utils.php
fp-includes/core/core.wp-formatting.php
fp-includes/fp-smartyplugins/validate_criteria.isEmail.php
fp-includes/fp-smartyplugins/validate_criteria.isURL.php
fp-includes/fp-smartyplugins/validate_criteria.notEmpty.php
fp-includes/smarty-4.5.5/libs/Smarty.class.php
fp-interface/lang/browserlang.php
fp-plugins/accessibleantispam/plugin.accessibleantispam.php
fp-plugins/bbcode/inc/stringparser.class.php
fp-plugins/photoswipe/photoswipefunctions.class.php

PHPDoc and small improvements 021

---

fp-plugins/photoswipe/photoswipefunctions.class.php

PHPDoc and small improvements 022

---

fp-plugins/bbcode/inc/stringparser.class.php
fp-plugins/bbcode/inc/stringparser_bbcode.class.php
fp-plugins/bbcode/plugin.bbcode.php
fp-plugins/mediamanager/panels/panel.mediamanager.file.php
fp-plugins/photoswipe/photoswipefunctions.class.php

PHPDoc and small improvements 023

---

fp-plugins/bbcode/inc/stringparser.class.php
fp-plugins/bbcode/plugin.bbcode.php
fp-plugins/commentcenter/inc/admin.php
fp-plugins/datechanger/plugin.datechanger.php
fp-plugins/prettyurls/plugin.prettyurls.php
fp-plugins/searchbox/plugin.searchbox.php
fp-plugins/seometataginfo/plugin.seometataginfo.php

PHPStan level 4 and turkish date format

PHPDoc and small improvements 024

---

fp-plugins/seometataginfo/plugin.seometataginfo.php

PHPDoc and small improvements 025

---

admin/panels/entry/admin.entry.list.php
admin/panels/static/admin.static.list.php
fp-includes/core/core.theme.php
fp-includes/fp-smartyplugins/resource.admin.php
fp-plugins/accessibleantispam/plugin.accessibleantispam.php
fp-plugins/bbcode/plugin.bbcode.php

PHPDoc and small improvements 026

---

admin/panels/uploader/admin.uploader.browse.php
admin/panels/uploader/admin.uploader.php
admin/panels/uploader/admin.uploader.thumb.php
fp-plugins/thumb/plugin.thumb.php

Thanks to Flo for this suggestion for improvement

add webp support | solves #611

---

admin/main.tpl
fp-includes/fp-smartyplugins/block.html_form.php

- No duplicate output of <form> ... </form>
- No duplicate output of id admin-{$panel}-{$subtab}

Solves #613 | Double output of <form> </form>

---

fp-includes/core/core.utils.php

Date/time according to RFC 5322 in the mail header

---

fp-plugins/newsletter/doc_newsletter.txt
fp-plugins/newsletter/plugin.newsletter.php

- Unwanted requests and bots are now intercepted more effectively: Suspicious IP addresses are automatically added to a block list, which is cleaned daily.
- Email addresses are now checked much more thoroughly—including domain and server checks—to detect typos, invalid, or undeliverable addresses.
- An up-to-date list of disposable email domains is automatically downloaded from GitHub once a month and integrated, so that disposable addresses are rejected immediately and removed from the subscriber list.
- In addition, the plugin limits the number of login attempts per IP and sorts out incorrect addresses before they are sent, ensuring that the newsletter is reliably delivered only to valid recipients.

Newsletter plugin: Update to version 1.7.0

---

fp-plugins/archives/plugin.archives.php
fp-plugins/archives/res/togglearchive.css
fp-plugins/archives/res/togglearchive.js

- Toggles in Themes, based on FlatMass 2 by Drudo

Update Archive plugin to v 1.1.1

---

fp-plugins/support/lang/lang.cs-cz.php
fp-plugins/support/lang/lang.da-dk.php
fp-plugins/support/lang/lang.de-de.php
fp-plugins/support/lang/lang.el-gr.php
fp-plugins/support/lang/lang.en-us.php
fp-plugins/support/lang/lang.es-es.php
fp-plugins/support/lang/lang.fr-fr.php
fp-plugins/support/lang/lang.it-it.php
fp-plugins/support/lang/lang.ja-jp.php
fp-plugins/support/lang/lang.nl-nl.php
fp-plugins/support/lang/lang.pt-br.php
fp-plugins/support/lang/lang.ru-ru.php
fp-plugins/support/lang/lang.sl-si.php
fp-plugins/support/lang/lang.tr-tr.php
fp-plugins/support/plugin.support.php
fp-plugins/support/tpls/admin.plugin.support.tpl

- Fixed: Theme without style causes PHP warning
- mbstring query added

Support plugin update to version 1.1.1

---

fp-includes/core/core.fpdb.class.php
fp-interface/themes/leggero/entry-default.tpl
fp-plugins/postviews/plugin.postviews.php

PostViews plugin without ugly core hack

---

fp-includes/fp-smartyplugins/function.views.php
fp-includes/fp-smartyplugins/prefilter.postviews_assign.php
fp-interface/themes/leggero/entry-default.tpl
fp-plugins/postviews/plugin.postviews.php

- Smarty {views} function and pre-filter

Fallback when PostViews plugin is disabled

---

defaults.php
fp-includes/core/core.connection.php

http vs https
