flatpressblog/flatpress

- fp-includes/core/core.system.php
Relating to issue #67, this just replaces a usage of `create_function()` with a native anonymous function.
`system_dpr()` doesn't seem to be called from anywhere _by default,_ but it may be useful when devs are debugging various things
> Migrate from create_func to native anon func | #67

- admin/panels/entry/admin.entry.write.tpl
- admin/panels/static/admin.static.write.tpl
- fp-plugins/seometataginfo/doc_seometataginfo.txt
- fp-plugins/seometataginfo/inc/class.iniparser.php
- fp-plugins/seometataginfo/inc/hw-helpers.php
- fp-plugins/seometataginfo/inc/migrate_data.php
- fp-plugins/seometataginfo/lang/lang.cs-cz.php
- fp-plugins/seometataginfo/lang/lang.de-de.php
- fp-plugins/seometataginfo/lang/lang.el-gr.php
- fp-plugins/seometataginfo/lang/lang.en-us.php
- fp-plugins/seometataginfo/lang/lang.es-es.php
- fp-plugins/seometataginfo/lang/lang.fr-fr.php
- fp-plugins/seometataginfo/lang/lang.it-it.php
- fp-plugins/seometataginfo/lang/lang.ja-jp.php
- fp-plugins/seometataginfo/lang/lang.nl-nl.php
- fp-plugins/seometataginfo/plugin.seometataginfo.php
*SEO Metatag Info Plugin in the standard distribution*
- includes all languages FlatPress currently supports as standard (translation via Deepl).
- Content customized texts incl. placeholder as example.
- With own hook in entry- and statictemplate, because otherwise the tag plugin is also shown when creating static pages; which is not supposed to be
With best regards
Frank
> solves issue #145

- comments.php
- fp-interface/lang/cs-cz/lang.comments.php
- fp-interface/lang/de-de/lang.comments.php
- fp-interface/lang/el-gr/lang.comments.php
- fp-interface/lang/en-us/lang.comments.php
- fp-interface/lang/es-es/lang.comments.php
- fp-interface/lang/fr-fr/lang.comments.php
- fp-interface/lang/it-it/lang.comments.php
- fp-interface/lang/ja-jp/lang.comments.php
- fp-interface/lang/nl-nl/lang.comments.php
- fp-interface/lang/pt-br/lang.comments.php
fixes #209 
Email notification is now sent when a new comment has been left and when the subject in the email header contains umlauts.
> for non-ASCII characters in the e-mail header

- fp-interface/themes/leggero/comments.tpl
Format for date and time in comments corrected
Fixes #237
> Format for date and time corrected

- fp-interface/themes/leggero/flatmaas-rev/res/admin.css
- fp-interface/themes/leggero/leggero-v2/res/admin.css
- fp-interface/themes/leggero/leggero/res/admin.css
Fixes #248 
* Prevents oversizing in the post-preview, when applying the code tag.
> Prevents oversizing in the post-preview, when applying the code tag.

- admin/panels/entry/admin.entry.write.tpl
- admin/panels/static/admin.static.write.tpl
- fp-interface/themes/leggero/cpheader.tpl
- fp-plugins/bbcode/plugin.bbcode.php
- fp-plugins/seometataginfo/lang/lang.cs-cz.php
- fp-plugins/seometataginfo/lang/lang.da-dk.php
- fp-plugins/seometataginfo/lang/lang.de-de.php
- fp-plugins/seometataginfo/lang/lang.el-gr.php
- fp-plugins/seometataginfo/lang/lang.en-us.php
- fp-plugins/seometataginfo/lang/lang.es-es.php
- fp-plugins/seometataginfo/lang/lang.fr-fr.php
- fp-plugins/seometataginfo/lang/lang.it-it.php
- fp-plugins/seometataginfo/lang/lang.ja-jp.php
- fp-plugins/seometataginfo/lang/lang.nl-nl.php
- fp-plugins/seometataginfo/lang/lang.pt-br.php
- fp-plugins/seometataginfo/lang/lang.ru-ru.php
- fp-plugins/seometataginfo/lang/lang.sl-si.php
- fp-plugins/seometataginfo/plugin.seometataginfo.php
- Fixes #184
- Fixes the problem when the SEOmetatagInfo plugin and/or [Tag plugin](https://wiki.flatpress.org/res:plugins:tag) were active that no new entries or static pages could be written. **Note:** Apparently the Smarty plugin [function.toolbar.php](https://github.com/flatpressblog/flatpress/blob/master/fp-includes/fp-smartyplugins/function.toolbar.php) does not work correctly with Smarty 4. Should be checked, as the [datechanger plugin](https://wiki.flatpress.org/res:plugins:datechanger) needs this.
- Fixes various HTML errors in the PHP code and in the templates. "Write static page" and "Write entry" are now largely valid for HTML5.
- The HTML code of the administration area now contains a lang attribute in the html start tag to specify the language.
- The "Save page" and …
> Revised static.write and entry.write panel in the administration area

- comments.php
- contact.php
- fp-includes/core/core.utils.php
- fp-plugins/commentcenter/plugin.commentcenter.php
- Instead of providing the mail subject with MIME base64 in different places, this has now been centralized.
> robust character encoding via core utils

- fp-plugins/footnotes/doc_footnotes.txt
- fp-plugins/footnotes/lang/lang.cs-cz.php
- fp-plugins/footnotes/lang/lang.da-dk.php
- fp-plugins/footnotes/lang/lang.de-de.php
- fp-plugins/footnotes/lang/lang.el-gr.php
- fp-plugins/footnotes/lang/lang.en-us.php
- fp-plugins/footnotes/lang/lang.es-es.php
- fp-plugins/footnotes/lang/lang.fr-fr.php
- fp-plugins/footnotes/lang/lang.it-it.php
- fp-plugins/footnotes/lang/lang.ja-jp.php
- fp-plugins/footnotes/lang/lang.nl-nl.php
- fp-plugins/footnotes/lang/lang.pt-br.php
- fp-plugins/footnotes/lang/lang.ru-ru.php
- fp-plugins/footnotes/lang/lang.sl-si.php
- fp-plugins/footnotes/plugin.footnotes.php
- Compatibility with [Markdown](https://github.com/flatpressblog/flatpress-extras/tree/master/fp-plugins/markdown) established
- The help document is now linked in the plugin panel
- Hard-coded output now localized
> Fixes #322

- fp-interface/themes/leggero/cpheader.tpl
- fp-interface/themes/leggero/header.tpl
- The Leggero template now uses the array locale.charset and can be changed via the admin panel Options->International settings->Character set.
`/fp-content/config/settings.conf.php
`
- https://forum.flatpress.org/viewtopic.php?t=323
- #281 ?
> Character set in the template

- fp-plugins/support/lang/lang.cs-cz.php
- fp-plugins/support/lang/lang.da-dk.php
- fp-plugins/support/lang/lang.de-de.php
- fp-plugins/support/lang/lang.el-gr.php
- fp-plugins/support/lang/lang.en-us.php
- fp-plugins/support/lang/lang.es-es.php
- fp-plugins/support/lang/lang.fr-fr.php
- fp-plugins/support/lang/lang.it-it.php
- fp-plugins/support/lang/lang.ja-jp.php
- fp-plugins/support/lang/lang.nl-nl.php
- fp-plugins/support/lang/lang.pt-br.php
- fp-plugins/support/lang/lang.ru-ru.php
- fp-plugins/support/lang/lang.sl-si.php
- fp-plugins/support/plugin.support.php
- fp-plugins/support/tpls/admin.plugin.support.tpl
- Support-Plugin: Indicates that the time zone correction in the configuration menu is skipped when the DateChanger plug-in is active
> Closes #350

- fp-defaults/plugins.conf.php
- fp-plugins/datechanger/doc_datechanger.txt
- fp-plugins/datechanger/plugin.datechanger.php
- fp-plugins/support/lang/lang.cs-cz.php
- fp-plugins/support/lang/lang.da-dk.php
- fp-plugins/support/lang/lang.de-de.php
- fp-plugins/support/lang/lang.el-gr.php
- fp-plugins/support/lang/lang.en-us.php
- fp-plugins/support/lang/lang.es-es.php
- fp-plugins/support/lang/lang.fr-fr.php
- fp-plugins/support/lang/lang.it-it.php
- fp-plugins/support/lang/lang.ja-jp.php
- fp-plugins/support/lang/lang.nl-nl.php
- fp-plugins/support/lang/lang.pt-br.php
- fp-plugins/support/lang/lang.ru-ru.php
- fp-plugins/support/lang/lang.sl-si.php
- fp-plugins/support/plugin.support.php
- fp-plugins/support/tpls/admin.plugin.support.tpl
- Note removed from support plugin
- DateChanger plugin is activated again as default
> Fixes #349 | DateChanger plugin: use UTC+timeoffset

- defaults.php
- fp-includes/core/core.cookie.php
#251
- if HTTP behind a load-balancer with a certificate (offloaded), but FlatPress needs HTTPS
- Solution by @rrossouw01 from https://github.com/flatpressblog/flatpress/issues/251#issuecomment-2071037862
> issue251-https-LB-Proxy

- setup/main.php
- If the absolute path is inconsistent, no file and directory permissions are set.
- Only a warning is stored in the error log.
This should solve #386
> Reworked: File and dir perms by setup

- index.php
- This offers the advantage that you can create a query in the header.tpl of a theme to determine whether a plugin is active or not.
This applies in my case:
`{if not function_exists('plugin_feed_head')} ... {/if} `
`{if not function_exists('plugin_searchbox_widget')} ... {/if}`
> Smarty modifier function 'function_exists'

- admin/panels/widgets/admin.widgets.default.php
- fp-defaults/settings-defaults.php
- fp-plugins/bbcode/res/editor.js
- fp-plugins/cookiebanner/plugin.cookiebanner.php
- fp-plugins/emoticons/plugin.emoticons.php
- fp-plugins/fpprotect/plugin.fpprotect.php
- fp-plugins/jquery/plugin.jquery.php
- fp-plugins/lightbox2/plugin.lightbox2.php
- fp-plugins/photoswipe/photoswipefunctions.class.php
- Emoticons and BBcode plugin no longer requires an inline-unsave source
- Replacement for href onclick HTML method in BBcode-toolbar and Emoticons-Toolbar
- This nonce attribute can be used in plugins, templates and in the admin area to ensure inline code even with stricter CSP version 3
**Description**
Scripts are integrated with a nonce (`<script nonce=“rAnd0m”....`). The hexadecimal value is changed each time the page is called. The variable is located in the array `$fp_config ['plugins'] ['fpprotect'] ['random_hex']` and can be included in templates with `{$fp_config.plugins.fpprotect.random_hex}`.
If required, this nonce can be pushed into the HTML response header as a directive via the FPProtect plugin. The client browser then checks whether a nonce value is stored in the script …
> Removes inline-unsave code | Solves #422

- fp-plugins/bbcode/lang/lang.cs-cz.php
- fp-plugins/bbcode/lang/lang.da-dk.php
- fp-plugins/bbcode/lang/lang.de-de.php
- fp-plugins/bbcode/lang/lang.el-gr.php
- fp-plugins/bbcode/lang/lang.en-us.php
- fp-plugins/bbcode/lang/lang.es-es.php
- fp-plugins/bbcode/lang/lang.fr-fr.php
- fp-plugins/bbcode/lang/lang.it-it.php
- fp-plugins/bbcode/lang/lang.ja-jp.php
- fp-plugins/bbcode/lang/lang.nl-nl.php
- fp-plugins/bbcode/lang/lang.pt-br.php
- fp-plugins/bbcode/lang/lang.ru-ru.php
- fp-plugins/bbcode/lang/lang.sl-si.php
- fp-plugins/bbcode/panels/admin.plugin.panel.bbcode.php
- fp-plugins/bbcode/plugin.bbcode.php
- fp-plugins/bbcode/res/editor.js
- fp-plugins/bbcode/tpls/admin.plugin.bbcode.tpl
- fp-plugins/bbcode/tpls/toolbar.tpl
- getfile.php
New function: when using the url tag in combination with a file from the attachments directory, the attachs directory is hidden in the URL. (Idea of NWM and DMKE).
without wrapper
with wrapper
- unsave inline onchange html-method removed (file/ image selection)
- Fixes #442
> BBcode plugin v1.9.0

- admin/panels/config/admin.config.php
- admin/panels/config/admin.config.tpl
- fp-defaults/settings-defaults.php
- fp-includes/core/core.utils.php
- fp-interface/lang/cs-cz/lang.admin.config.php
- fp-interface/lang/da-dk/lang.admin.config.php
- fp-interface/lang/de-de/lang.admin.config.php
- fp-interface/lang/el-gr/lang.admin.config.php
- fp-interface/lang/en-us/lang.admin.config.php
- fp-interface/lang/es-es/lang.admin.config.php
- fp-interface/lang/fr-fr/lang.admin.config.php
- fp-interface/lang/it-it/lang.admin.config.php
- fp-interface/lang/ja-jp/lang.admin.config.php
- fp-interface/lang/nl-nl/lang.admin.config.php
- fp-interface/lang/pt-br/lang.admin.config.php
- fp-interface/lang/ru-ru/lang.admin.config.php
- fp-interface/lang/sl-si/lang.admin.config.php
* For IPv4 addresses, the last two blocks are “zeroed”
* IPv6 addresses are replaced by a hash, which is formed from the user agent and the browser language
This procedure has the advantage that other scripts do not have to be adapted, as a fake IPv4 or IPv6 is still available. Optionally, the anonymization of the visitor IP can be deactivated in the admin area.
> Fixes #105 | Anonymize visitor IP

- fp-plugins/commentcenter/plugin.commentcenter.php
- fp-plugins/qspam/plugin.qspam.php
- Fixes the problem that other comment filters do not work if the corresponding plugins are loaded alphabetically.
Discovered by [Ross Fruen](https://www.gsys.biz/blog/reducing-priority-of-flatpress-comment-center/) and [broken down](https://www.robertriebisch.de/2022/05/flatpress-nachschlag-zum-kommentarspam) by @bttrx
With this fix, comments filtered by the QuickSpam plugin are immediately rejected and do not have to be manually rejected by the FP admin in the comment center.
> Comment filters act according to priority, not alphabetically

- fp-plugins/calendar/plugin.calendar.php
- This solves #73 and #128.
- Two new functions which only output a “Next” or “Previous” link if there is at least one entry in the month.
- The “Next”, “Previous” and “Day” links now always contain a 4-digit year.
- The set language is now taken into account when determining the first day of the week.
- Single-digit months are now always two-digit.
> Update Calendar Plugin tu 1.2

- fp-plugins/bbcode/plugin.bbcode.php
- fp-plugins/gdprvideoembed/plugin.gdprvideoembed.php
- fp-plugins/gdprvideoembed/res/gdpr-video-embed.js
- The non-dynamic Java code has been outsourced to a file in favor of loading times.
- An external link for Facebook video is now also displayed.
> GDPR video embed with external Facebook video link

- fp-interface/themes/leggero/entry-default.tpl
- The “Add comment” link now also leads to the CSS ID #addcomment instead of the non-existent CSS ID #comments
> Fixes #474 |  Poor user-friendliness in the “Add comment” link

- fp-includes/core/core.date.php
- fp-includes/core/core.theme.php
**Improvements:**
- The strftime_replacement function now correctly throws objects of type Exception Error.
- The combination of format, time zone and locale is now cached to reduce IntlDateFormatter objects and save memory.
Before `new \DateTimeZone($timezone)` is called, it is checked whether the time zone passed is contained in the list of valid time zones (`\DateTimeZone::listIdentifiers()`). If not, the time zone is set to 'UTC' to ensure that no error occurs.
- It is now ensured that no infinite loop is created in the callback function for `preg_replace_callback()` and that invalid or unhandled format characters are properly intercepted.
- If no timestamp (0, null invalid) is passed to the `date_strformat` function, the timestamp is determined using the `date_time function`.
- In …
> Fixes the bug: Can only throw objects

- fp-plugins/fpprotect/lang/lang.cs-cz.php
- fp-plugins/fpprotect/lang/lang.da-dk.php
- fp-plugins/fpprotect/lang/lang.de-de.php
- fp-plugins/fpprotect/lang/lang.el-gr.php
- fp-plugins/fpprotect/lang/lang.en-us.php
- fp-plugins/fpprotect/lang/lang.es-es.php
- fp-plugins/fpprotect/lang/lang.fr-fr.php
- fp-plugins/fpprotect/lang/lang.it-it.php
- fp-plugins/fpprotect/lang/lang.ja-jp.php
- fp-plugins/fpprotect/lang/lang.nl-nl.php
- fp-plugins/fpprotect/lang/lang.pt-br.php
- fp-plugins/fpprotect/lang/lang.ru-ru.php
- fp-plugins/fpprotect/lang/lang.sl-si.php
- fp-plugins/fpprotect/plugin.fpprotect.php
- A warning is now displayed if the script-src directive contains “unsafe-inline”
> Shows a warning if unsafe-inline

- fp-plugins/photoswipe/plugin.photoswipe.php
- Fixes the problem that the overlay bottons were displayed in the RSS and Atom feed
- The system now checks whether an RSS or Atom feed is called up or not. If a feed is called, the other PhotoSwipe files are simply not loaded.
> Update PhotoSwipe plugin to version 2.0.1

- admin/panels/entry/admin.entry.commedit.php
- fp-includes/core/core.comment.php
- Fixes the error "Undefined variable $success" under PHP8.4
- Solves the problem that the admin can only edit his own comments.
- _checkFile: Return of null made explicit to fulfill the strictness of PHP 8+.
> The logged-in admin can now also edit other comments

- fp-plugins/lastcomments/plugin.lastcomments.php
Hi @azett,
I can also reproduce it. Once with my test system without cache mechanisms, but also on Pi, with the production system. However, I firmly believe that it is not a side effect of #499. When the configuration menu page is reloaded (F5), only the currently set lang_load language is loaded.
The language arrays for the configuration menu were only assigned to the template after reloading the page until 1.3.1. For users with OPcache and/or APCu, nothing happened after clicking on “Save change”. Saved changes were only loaded after reloading the configuration page. Therefore the 18 year old problem was never noticed. Now onsave() with setup() immediately pushes the changed keys into the template. And now we have two keys in lang_load - 0 and 1. After reloading the page, everything is …
> Fixes #517 |  "Array to string conversion" warning

- fp-includes/core/core.language.php
- fp-includes/core/core.system.php
- search.php
- Plugins can access locale information
- Smarty templates could use functions that require locale information (e.g. date formats or localization strings).
Sequence:
- Before loading plugins
- Before Smarty initialization
- After loading the language configuration
This sequence ensures that all dependent components use the correct locale settings.
> Update set_locale function

- fp-includes/core/core.cookie.php
- fp-includes/core/core.language.php
- See [forum post by Laborix](https://forum.flatpress.org/viewtopic.php?t=828&sid=1b47a2f44a4d87f68cab19d537a1d714&start=20#p2957)
> Timeout for shell_exec call | More stability in session handling

- fp-plugins/photoswipe/photoswipefunctions.class.php
- fp-plugins/photoswipe/plugin.photoswipe.php
- fp-plugins/photoswipe/res/photoswipe-4.1.3/photoswipe.js
- fp-plugins/photoswipe/res/photoswipe.js.php
- keyboard focus is restored for screen readers after closing the overlay
- You can also remove the ugly .readmore hack from ddebf34 from the inline script again
- Ensures that .pswp is always in the DOM. See #572
> Solves #622 and #572 | makes PhotoSwipe a11y

- setup/main.php
- Avoids problems with open_basedir restrictions and when reading is not possible due to access rights
- Solves a possible problem that [qbwdp had in the support forum](https://forum.flatpress.org/viewtopic.php?p=3109#p3105).
> Safe resolution of the path

- fp-includes/core/core.smarty.php
- fp-includes/core/core.theme.php
- fp-includes/core/core.utils.php
- fp-includes/core/includes.php
- fp-includes/fp-smartyplugins/modifier.ver.php
- fp-plugins/archives/plugin.archives.php
- fp-plugins/bbcode/plugin.bbcode.php
- fp-plugins/commentcenter/inc/admin.php
- fp-plugins/cookiebanner/plugin.cookiebanner.php
- fp-plugins/emoticons/plugin.emoticons.php
- fp-plugins/favicon/plugin.favicon.php
- fp-plugins/feed/plugin.feed.php
- fp-plugins/gdprvideoembed/plugin.gdprvideoembed.php
- fp-plugins/jquery/plugin.jquery.php
- fp-plugins/mediamanager/tpls/admin.plugin.mediamanager.files.tpl
- fp-plugins/photoswipe/photoswipefunctions.class.php
- fp-plugins/support/plugin.support.php
- Sets/replaces a query parameter in a URL (RFC-3986)
- New Smarty modifier |ver – appends ?v=… (see utils_asset_ver()).
- Use in the template: 
- `<script src={“ /editor.js”|ver}></script>`
- `<link rel="stylesheet" href={“/css/app.css”|ver:$smarty.const.SYSTEM_VER}>
`
- New core function utils_asset_ver()
- Priority:
- $version (explicit) > filemtime (local file) > SYSTEM_VER (fallback).
- Use in PHP code, e.g.: Plugins:
- `utils_asset_ver($url[, $version]) Example: $js = utils_asset_ver($pdir . ‘res/cookiebanner.js’, SYSTEM_VER);`
> Solves #629 | Versioning Java scripts and stylesheets (RFC-3986)

- fp-interface/themes/leggero/comments.tpl
- fp-interface/themes/leggero/entry-default.tpl
- fp-interface/themes/leggero/preview.tpl
- `theme_date_format()` correctly falls back to `$fp_config[‘locale’][‘timeformat’]` without a format.
- However, in a fresh installation, the built-in Smarty modifier date_format often uses the default format “%b %e, %Y” → display as “Aug 31,” instead of the time.
- It is safer to explicitly pass the time format.
- Only output “in” if a category is specified for a post.
> Date and time format in templates

- fp-includes/core/core.entry.php
- fp-includes/core/core.fileio.php
- fileio core
- entries core
Note for this development stage:
```
Load scenario: 3,000 posts × 5 comments.
Search (search.php) touches most entries and dominates memory.
Peak calculation:
fp:io:*
3,000 × ~1.93 KiB + 15,000 × ~0.52 KiB ≈ 13.3 MiB
fp:entry:parsed:* (TTL 600 s, e.g. after search)
3,000 × ~1.98 KiB ≈ 6.0 MiB
Plugins/Smarty/other: ~2–3 MiB
Worst-case simultaneously ≈ 21–23 MiB < 32 MiB; headroom ≈ 9–11 MiB covers fragmentation.
Note: APCu is a shared pool per FPM pool (apc.shm_size), not per child process.
```
> Use of the local cache and optional APCu
